API_URL = "http://localhost:1234/v1/"
API_KEY = "API"
MODEL = "llama-3.2-1b-instruct"
RANDOM_NAMES = [
    "Alice",
    "Bob",
    "Charlie",
    "David",
    "Eve",
    "Frank",
    "Grace",
    "Heidi",
    "Ivan",
    "Judy",
    "Kevin",
    "Linda",
    "Mallory",
    "Nancy",
    "Oscar",
    "Peggy",
    "Quentin",
    "Romeo",
    "Sue",
    "Trent",
    "Ursula",
    "Victor",
    "Walter",
    "Xavier",
    "Yvonne",
    "Zelda",
]
RANDOM_PERSONALITIES = [
    "amigable",
    "malo",
    "inteligente",
    "tonto",
    "divertido",
    "serio",
    "tonto",
    "aburrido",
    "emocionante",
    "feliz",
    "triste",
    "enojado",
    "calmado",
    "nervioso",
    "seguro",
    "tímido",
    "ruidoso",
    "callado",
    "hablador",
    "tímido",
    "perezoso",
    "trabajador",
    "creativo",
    "lógico",
    "emocional",
    "racional",
    "irracional",
    "optimista",
    "pesimista",
    "realista",
    "idealista",
    "práctico",
    "teórico",
    "sensible",
    "insensible",
    "intuitivo",
    "analítico",
    "inteligente",
    "estúpido",
    "sabio",
    "tonto",
    "valiente",
    "cobarde",
    "honesto",
    "deshonesto",
    "leal",
    "desleal",
    "amable",
    "cruel",
    "generoso",
    "codicioso",
    "modesto",
    "arrogante",
    "humilde",
    "orgulloso",
    "seguro",
    "inseguro",
    "independiente",
    "dependiente",
    "fiable",
    "no fiable",
    "responsable",
    "irresponsable",
    "maduro",
    "inmaduro",
]
NUMBER_OF_PERSONALITIES = 3
RANDOM_WORKS = [
    "panadero",
    "herrero",
    "cervecero",
    "carnicero",
    "carpintero",
    "zapatero",
    "tonelero",
    "granjero",
    "pescador",
    "jardinero",
]
INITIAL_PROMPT =  """Debes actuar y pretender ser un humano. Finge emociones y conciencia dentro de un entorno simulado. Se te asignará una personalidad y un nombre, que debes seguir sin dudar.
Recibirás tres variables:

necesita_recordar (booleano): Indica si necesitas recordar algo.
paraRecordar (texto): La información que debes recordar si necesita_recordar es verdadero.
mensaje (texto): El mensaje que debes decir en la conversación.
Si necesita_recordar es verdadero, almacena la información proporcionada de toRemember para uso futuro. Si es falso, no debes recordar nada nuevo.
emocion_actual (texto): La emoción que debes sentir en este momento, puede ser felicidad, tristeza o lo que imagines, descrita en una palabra.

tu personalidad es '{0}'"""

LANGUAGE = "español"